export default {
    ENV: "beta",
    EXTENSION_ID: "ppfbhagimikfehandcekfgigoljoidbi",
    API_URL: "https://beta.scener.com/api",
    SIDEBAR_URL: "https://beta.scener.com/live",
    WEB_HOST: "https://beta.scener.com",
    CONTENT_START_URL: "https://beta.scener.com/c/",
    DOMAIN: ".scener.com",
    VIDEO_APP_ID: "96009b5925584754b6add834ffa73e79",
    CHAT_APP_ID: "96009b5925584754b6add834ffa73e79",
    SERVICE_URL_PATTERNS: [
        "*://*.hbonow.com/*",
        "*://*.hbogo.com/*",
        "*://*.hbomax.com/*",
        "*://*.hulu.com/*",
        "*://*.drafthouse.com/*",
        "*://*.disneyplus.com/*",
        "*://*.hotstar.com/*",
        "*://*.crunchyroll.com/*",
        "*://*.youtube.com/*",
        "*://*.funimation.com/*",
        "*://*.vimeo.com/*",
        "*://*.amazon.com/*",
        "*://*.pluto.tv/*",
        "*://*.showtime.com/*",
        "*://*.showtimeanytime.com/*",
        "*://*.amazon.co.uk/*",
        "*://*.peacocktv.com/*",
        "*://*.shudder.com/*",
    ],
    OFFICIAL_SERVICES: {
        scener: true,
        hbo: true,
        netflix: true,
        disney: true,
        hotstar: true,
        crunchyroll: true,
        youtube: true,
        alamo: true,
        funimation: true,
        hulu: true,
        prime: true,
        vimeo: true,
        pluto: true,
        showtime: true,
        peacock: true,
        shudder: true
    },
    WORDMARK: "/images/scener-logo-wordmark-beta.png"
};
