export default {
    ENV: "prod",
    API_URL: "https://scener.com/api",
    EXTENSION_ID: "lkhjgdkpibcepflmlgahofcmeagjmecc",
    CONTENT_START_URL: "https://scener.com/c/",
    WEB_HOST: "https://scener.com",
    SIDEBAR_URL: "https://scener.com/live",

    DOMAIN: ".scener.com",
    VIDEO_APP_ID: "96009b5925584754b6add834ffa73e79",
    CHAT_APP_ID: "96009b5925584754b6add834ffa73e79",
    SERVICE_URL_PATTERNS: [
        "*://*.hbonow.com/*",
        "*://*.hbogo.com/*",
        "*://*.hbomax.com/*",
        "*://*.hulu.com/*",
        "*://*.disneyplus.com/*",
        "*://*.hotstar.com/*",
        "*://*.crunchyroll.com/*",
        "*://*.youtube.com/*",
        "*://*.funimation.com/*",
        "*://*.drafthouse.com/*",
        "*://*.vimeo.com/*",
        "*://*.amazon.com/*",
        "*://*.pluto.tv/*",
        "*://*.shudder.com/*",
        "*://*.showtime.com/*",
        "*://*.showtimeanytime.com/*",
        "*://*.amazon.co.uk/*",
    ],

    OFFICIAL_SERVICES: {
        scener: true,
        hbo: true,
        netflix: true,
        disney: true,
        hotstar: false,
        crunchyroll: false,
        youtube: true,
        alamo: true,
        funimation: true,
        hulu: true,
        prime: true,
        vimeo: true,
        pluto: false,
        showtime: false,
        peacock: false,
        shudder: true
    },
    WORDMARK: "/images/scener-logo-wordmark.png"
};
